/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
export interface AccountDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Account role */
  role: string;
  /** Account sign in type */
  signInType: string;
  nickname: string;
  avatarFileName: string;
  avatarUrl: string;
  /**
   * 진입 시점
   * @nullable
   */
  enteredAt: string | null;
  /** @nullable */
  leftAt: string | null;
  isActive: boolean;
}

export interface ActiveAccountCountDto {
  count: number;
}

export interface AccountCollectionDto {
  data: AccountDto[];
}

export interface AccountAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Account role */
  role: string;
  /** Account sign in type */
  signInType: string;
  nickname: string;
  avatarFileName: string;
  avatarUrl: string;
  /**
   * 진입 시점
   * @nullable
   */
  enteredAt: string | null;
  /** @nullable */
  leftAt: string | null;
  isActive: boolean;
}

export interface AccountCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: AccountAdminDto[];
}

export interface UpdateAccountDto {
  nickname?: string;
  avatarFileName?: string;
}

export interface SignUpWithUsernameDto {
  username: string;
  password: string;
}

export interface AuthTokenDto {
  accessToken: string;
}

export interface SignInWithUsernameDto {
  username: string;
  password: string;
}

export interface CreateAvatarDto {
  file: Blob;
  /** @minLength 1 */
  name?: string;
  /** 아바타 설명 */
  description?: string;
}

export interface AvatarAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  originalFileName: string;
  avatarFileName: string;
  avatarImageUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  width: number;
  height: number;
  /** @nullable */
  description: string | null;
  usageCount: number;
}

export interface AvatarCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: AvatarAdminDto[];
}

export interface UpdateAvatarAdminDto {
  /** @minLength 1 */
  name?: string;
  /** @nullable */
  description?: string | null;
}

export interface CreateGameRoomDto {
  /**
   * 게임 방 제목
   * @minLength 1
   * @maxLength 50
   */
  title: string;
  /**
   * @minimum 10
   * @maximum 100
   */
  quizzesCount: number;
}

export type GameRoomMemberDtoRole = typeof GameRoomMemberDtoRole[keyof typeof GameRoomMemberDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameRoomMemberDtoRole = {
  host: 'host',
  player: 'player',
} as const;

export interface GameRoomMemberDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  gameRoomId: string;
  role: GameRoomMemberDtoRole;
  /** 게임방 구성원의 닉네임(계정 닉네임과 동일함) */
  nickname: string;
  avatarUrl: string;
}

export type GameRoomDtoStatus = typeof GameRoomDtoStatus[keyof typeof GameRoomDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameRoomDtoStatus = {
  waiting: 'waiting',
  starting: 'starting',
  inProgress: 'inProgress',
  finished: 'finished',
  paused: 'paused',
} as const;

export interface GameRoomDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  hostId: string;
  status: GameRoomDtoStatus;
  title: string;
  maxMembersCount: number;
  currentMembersCount: number;
  quizTimeLimitInSeconds: number;
  quizzesCount: number;
  members: GameRoomMemberDto[];
}

export interface GameRoomMemberCollectionDto {
  data: GameRoomMemberDto[];
}

export interface GameRoomCollectionDto {
  data: GameRoomDto[];
}

export interface CreateNicknameSourceAdminDto {
  /**
   * @minLength 1
   * @maxLength 10
   */
  name: string;
}

export interface NicknameSourceAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  sequence: number;
  fullname: string;
}

export interface NicknameSourceCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: NicknameSourceAdminDto[];
}

export interface UpdateNicknameSourceAdminDto {
  /**
   * @minLength 1
   * @maxLength 10
   */
  name?: string;
}

export interface CreateQuizzesAdminDto {
  type: string;
  answer: string;
  /** @nullable */
  question: string | null;
  /** @nullable */
  imageFileName: string | null;
}

export interface QuizAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** 퀴즈 유형 */
  type: string;
  /**
   * 퀴즈 질문
   * @nullable
   */
  question: string | null;
  /** 퀴즈 정답 */
  answer: string;
  /**
   * 퀴즈 이미지 파일명
   * @nullable
   */
  imageFileName: string | null;
  /**
   * 퀴즈 이미지 URL
   * @nullable
   */
  imageUrl: string | null;
}

export interface QuizCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: QuizAdminDto[];
}

export interface UpdateQuizAdminDto {
  type?: string;
  answer?: string;
  /** @nullable */
  question?: string | null;
  /** @nullable */
  imageFileName?: string | null;
}

export interface CreateQuizImageAdminDto {
  /** quiz image file */
  file: Blob;
  /** quiz image category */
  category: string;
  /** @minLength 1 */
  name?: string;
}

export interface QuizImageAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  category: string;
  name: string;
  originalFileName: string;
  quizImageFileName: string;
  quizImageUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  width: number;
  height: number;
}

export interface QuizImageCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: QuizImageAdminDto[];
}

export interface UpdateQuizImageAdminDto {
  /** @minLength 1 */
  name?: string;
  category?: string;
}

export interface CreateSoundEffectDto {
  file: Blob;
  /** @minLength 1 */
  name?: string;
  description?: string;
}

export interface SoundEffectAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  originalFileName: string;
  soundEffectFileName: string;
  soundEffectUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  /** @nullable */
  description: string | null;
}

export interface SoundEffectDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  originalFileName: string;
  soundEffectFileName: string;
  soundEffectUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  /** @nullable */
  description: string | null;
}

export interface SoundEffectCollectionDto {
  data: SoundEffectDto[];
}

export interface SoundEffectCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: SoundEffectAdminDto[];
}

export interface UpdateSoundEffectAdminDto {
  /** @minLength 1 */
  name?: string;
  /** @nullable */
  description?: string | null;
}

export type SignInWithGoogleControllerSignInWithGoogleParams = {
redirectUrl?: string;
};

/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername400Code = typeof SignUpWithUsernameControllerSignUpWithUsername400Code[keyof typeof SignUpWithUsernameControllerSignUpWithUsername400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUpWithUsernameControllerSignUpWithUsername400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type SignUpWithUsernameControllerSignUpWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername400Code;
};

/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername409Code = typeof SignUpWithUsernameControllerSignUpWithUsername409Code[keyof typeof SignUpWithUsernameControllerSignUpWithUsername409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUpWithUsernameControllerSignUpWithUsername409Code = {
  ACCOUNTUSERNAME_ALREADY_OCCUPIED: 'ACCOUNT.USERNAME_ALREADY_OCCUPIED',
} as const;

export type SignUpWithUsernameControllerSignUpWithUsername409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername409Code;
};

/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername400Code = typeof SignInWithUsernameControllerSignInWithUsername400Code[keyof typeof SignInWithUsernameControllerSignInWithUsername400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignInWithUsernameControllerSignInWithUsername400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type SignInWithUsernameControllerSignInWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername400Code;
};

/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername401Code = typeof SignInWithUsernameControllerSignInWithUsername401Code[keyof typeof SignInWithUsernameControllerSignInWithUsername401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignInWithUsernameControllerSignInWithUsername401Code = {
  AUTHSIGN_IN_INFO_NOT_MATCHED: 'AUTH.SIGN_IN_INFO_NOT_MATCHED',
} as const;

export type SignInWithUsernameControllerSignInWithUsername401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername401Code;
};

