/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
import type {
  QuizCollectionDto
} from './quizzesGameIoBackend.schemas';

import { orvalInstance } from '../../../shared/service/api/client/index';



  /**
 * @summary 퀴즈 목록 조회
 */
export const listQuizzesControllerListQuizzes = (
    
 ) => {
      return orvalInstance<QuizCollectionDto>(
      {url: `/admin/quizzes`, method: 'GET'
    },
      );
    }
  
export type ListQuizzesControllerListQuizzesResult = NonNullable<Awaited<ReturnType<typeof listQuizzesControllerListQuizzes>>>
