/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as menusRouteRouteImport } from './routes/(menus)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as menusQuizzesIndexRouteImport } from './routes/(menus)/quizzes/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'

const menusRouteRoute = menusRouteRouteImport.update({
  id: '/(menus)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const menusQuizzesIndexRoute = menusQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => menusRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof menusRouteRouteWithChildren
  '/login': typeof authLoginIndexRoute
  '/quizzes': typeof menusQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof menusRouteRouteWithChildren
  '/login': typeof authLoginIndexRoute
  '/quizzes': typeof menusQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(menus)': typeof menusRouteRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(menus)/quizzes/': typeof menusQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/quizzes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(menus)'
    | '/(auth)/login/'
    | '/(menus)/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  menusRouteRoute: typeof menusRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(menus)': {
      id: '/(menus)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof menusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(menus)/quizzes/': {
      id: '/(menus)/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof menusQuizzesIndexRouteImport
      parentRoute: typeof menusRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface menusRouteRouteChildren {
  menusQuizzesIndexRoute: typeof menusQuizzesIndexRoute
}

const menusRouteRouteChildren: menusRouteRouteChildren = {
  menusQuizzesIndexRoute: menusQuizzesIndexRoute,
}

const menusRouteRouteWithChildren = menusRouteRoute._addFileChildren(
  menusRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  menusRouteRoute: menusRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
