/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
export interface AccountDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Account role */
  role: string;
  /** Account sign in type */
  signInType: string;
  nickname: string;
  /** 진입 시점 */
  enteredAt: string;
  leftAt: string;
  isActive: boolean;
}

export interface AccountCollectionDto {
  data: AccountDto[];
}

export interface SignUpWithUsernameDto {
  username: string;
  password: string;
}

export interface AuthTokenDto {
  accessToken: string;
}

export interface SignInWithUsernameDto {
  username: string;
  password: string;
}

export interface CreateGameRoomDto {
  /**
   * 게임 방 제목
   * @minLength 1
   * @maxLength 50
   */
  title: string;
  /**
   * @minimum 10
   * @maximum 100
   */
  quizzesCount: number;
}

export type GameRoomMemberDtoRole =
  (typeof GameRoomMemberDtoRole)[keyof typeof GameRoomMemberDtoRole];

export const GameRoomMemberDtoRole = {
  host: 'host',
  player: 'player',
} as const;

export interface GameRoomMemberDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  gameRoomId: string;
  role: GameRoomMemberDtoRole;
  /** 게임방 구성원의 닉네임(계정 닉네임과 동일함) */
  nickname: string;
}

export type GameRoomDtoStatus =
  (typeof GameRoomDtoStatus)[keyof typeof GameRoomDtoStatus];

export const GameRoomDtoStatus = {
  waiting: 'waiting',
  starting: 'starting',
  inProgress: 'inProgress',
  finished: 'finished',
  paused: 'paused',
} as const;

export interface GameRoomDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  hostId: string;
  status: GameRoomDtoStatus;
  title: string;
  maxMembersCount: number;
  currentMembersCount: number;
  quizTimeLimitInSeconds: number;
  quizzesCount: number;
  members: GameRoomMemberDto[];
}

export interface GameRoomMemberCollectionDto {
  data: GameRoomMemberDto[];
}

export interface GameRoomCollectionDto {
  data: GameRoomDto[];
}

export interface CreateImageDto {
  /** image file */
  file: Blob;
  /** image category */
  category: string;
}

export interface ImageDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  category: string;
  originalFileName: string;
  imageUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  width: number;
  height: number;
}

export interface ImageCollectionDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: ImageDto[];
}

export interface CreateNicknameSourceDto {
  /**
   * @minLength 1
   * @maxLength 10
   */
  name: string;
}

export interface NicknameSourceDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  sequence: number;
  fullname: string;
}

export interface CreateQuizzesDto {
  type: string;
  answer: string;
  /** @nullable */
  question: string | null;
  /** @nullable */
  imageUrl: string | null;
}

export interface QuizDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** 퀴즈 유형 */
  type: string;
  /**
   * 퀴즈 질문
   * @nullable
   */
  question: string | null;
  /** 퀴즈 정답 */
  answer: string;
  /**
   * 퀴즈 이미지 URL
   * @nullable
   */
  imageUrl: string | null;
}

export interface QuizCollectionDto {
  data: QuizDto[];
}

export interface UpdateQuizDto {
  type?: string;
  answer?: string;
  /** @nullable */
  question?: string | null;
  /** @nullable */
  imageUrl?: string | null;
}

/**
 * error code
 */
export type CreateImageControllerCreateImageAdmin400Code =
  (typeof CreateImageControllerCreateImageAdmin400Code)[keyof typeof CreateImageControllerCreateImageAdmin400Code];

export const CreateImageControllerCreateImageAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateImageControllerCreateImageAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateImageControllerCreateImageAdmin400Code;
};

/**
 * error code
 */
export type CreateImageControllerCreateImageAdmin401Code =
  (typeof CreateImageControllerCreateImageAdmin401Code)[keyof typeof CreateImageControllerCreateImageAdmin401Code];

export const CreateImageControllerCreateImageAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateImageControllerCreateImageAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateImageControllerCreateImageAdmin401Code;
};

/**
 * error code
 */
export type CreateImageControllerCreateImageAdmin403Code =
  (typeof CreateImageControllerCreateImageAdmin403Code)[keyof typeof CreateImageControllerCreateImageAdmin403Code];

export const CreateImageControllerCreateImageAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateImageControllerCreateImageAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateImageControllerCreateImageAdmin403Code;
};

export type ListImagesControllerListImagesAdminParams = {
  /**
   * 카테고리 필터링
   */
  category?: string;
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 5
   * @maximum 1000
   */
  perPage?: number;
};

/**
 * error code
 */
export type ListImagesControllerListImagesAdmin400Code =
  (typeof ListImagesControllerListImagesAdmin400Code)[keyof typeof ListImagesControllerListImagesAdmin400Code];

export const ListImagesControllerListImagesAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type ListImagesControllerListImagesAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListImagesControllerListImagesAdmin400Code;
};

/**
 * error code
 */
export type ListImagesControllerListImagesAdmin401Code =
  (typeof ListImagesControllerListImagesAdmin401Code)[keyof typeof ListImagesControllerListImagesAdmin401Code];

export const ListImagesControllerListImagesAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type ListImagesControllerListImagesAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListImagesControllerListImagesAdmin401Code;
};

/**
 * error code
 */
export type ListImagesControllerListImagesAdmin403Code =
  (typeof ListImagesControllerListImagesAdmin403Code)[keyof typeof ListImagesControllerListImagesAdmin403Code];

export const ListImagesControllerListImagesAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type ListImagesControllerListImagesAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListImagesControllerListImagesAdmin403Code;
};

/**
 * error code
 */
export type DeleteImageControllerDeleteImage400Code =
  (typeof DeleteImageControllerDeleteImage400Code)[keyof typeof DeleteImageControllerDeleteImage400Code];

export const DeleteImageControllerDeleteImage400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type DeleteImageControllerDeleteImage400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteImageControllerDeleteImage400Code;
};

/**
 * error code
 */
export type DeleteImageControllerDeleteImage401Code =
  (typeof DeleteImageControllerDeleteImage401Code)[keyof typeof DeleteImageControllerDeleteImage401Code];

export const DeleteImageControllerDeleteImage401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type DeleteImageControllerDeleteImage401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteImageControllerDeleteImage401Code;
};

/**
 * error code
 */
export type DeleteImageControllerDeleteImage403Code =
  (typeof DeleteImageControllerDeleteImage403Code)[keyof typeof DeleteImageControllerDeleteImage403Code];

export const DeleteImageControllerDeleteImage403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type DeleteImageControllerDeleteImage403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteImageControllerDeleteImage403Code;
};

/**
 * error code
 */
export type DeleteImageControllerDeleteImage404Code =
  (typeof DeleteImageControllerDeleteImage404Code)[keyof typeof DeleteImageControllerDeleteImage404Code];

export const DeleteImageControllerDeleteImage404Code = {
  IMAGENOT_FOUND: 'IMAGE.NOT_FOUND',
} as const;

export type DeleteImageControllerDeleteImage404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteImageControllerDeleteImage404Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code = {
  NICKNAME_SOURCEALREADY_EXISTS: 'NICKNAME_SOURCE.ALREADY_EXISTS',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code;
};

/**
 * error code
 */
export type CreateQuizzesControllerCreateQuizzesAdmin400Code =
  (typeof CreateQuizzesControllerCreateQuizzesAdmin400Code)[keyof typeof CreateQuizzesControllerCreateQuizzesAdmin400Code];

export const CreateQuizzesControllerCreateQuizzesAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateQuizzesControllerCreateQuizzesAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizzesControllerCreateQuizzesAdmin400Code;
};

/**
 * error code
 */
export type CreateQuizzesControllerCreateQuizzesAdmin401Code =
  (typeof CreateQuizzesControllerCreateQuizzesAdmin401Code)[keyof typeof CreateQuizzesControllerCreateQuizzesAdmin401Code];

export const CreateQuizzesControllerCreateQuizzesAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateQuizzesControllerCreateQuizzesAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizzesControllerCreateQuizzesAdmin401Code;
};

/**
 * error code
 */
export type CreateQuizzesControllerCreateQuizzesAdmin403Code =
  (typeof CreateQuizzesControllerCreateQuizzesAdmin403Code)[keyof typeof CreateQuizzesControllerCreateQuizzesAdmin403Code];

export const CreateQuizzesControllerCreateQuizzesAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateQuizzesControllerCreateQuizzesAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizzesControllerCreateQuizzesAdmin403Code;
};

/**
 * error code
 */
export type ListQuizzesControllerListQuizzes400Code =
  (typeof ListQuizzesControllerListQuizzes400Code)[keyof typeof ListQuizzesControllerListQuizzes400Code];

export const ListQuizzesControllerListQuizzes400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type ListQuizzesControllerListQuizzes400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizzesControllerListQuizzes400Code;
};

/**
 * error code
 */
export type ListQuizzesControllerListQuizzes401Code =
  (typeof ListQuizzesControllerListQuizzes401Code)[keyof typeof ListQuizzesControllerListQuizzes401Code];

export const ListQuizzesControllerListQuizzes401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type ListQuizzesControllerListQuizzes401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizzesControllerListQuizzes401Code;
};

/**
 * error code
 */
export type ListQuizzesControllerListQuizzes403Code =
  (typeof ListQuizzesControllerListQuizzes403Code)[keyof typeof ListQuizzesControllerListQuizzes403Code];

export const ListQuizzesControllerListQuizzes403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type ListQuizzesControllerListQuizzes403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizzesControllerListQuizzes403Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin400Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin400Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin400Code];

export const DeleteQuizControllerDeleteQuizAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin400Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin401Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin401Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin401Code];

export const DeleteQuizControllerDeleteQuizAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin401Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin403Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin403Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin403Code];

export const DeleteQuizControllerDeleteQuizAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin403Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin404Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin404Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin404Code];

export const DeleteQuizControllerDeleteQuizAdmin404Code = {
  QUIZNOT_FOUND: 'QUIZ.NOT_FOUND',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin404Code;
};

/**
 * error code
 */
export type GetQuizControllerGetQuizzesAdmin400Code =
  (typeof GetQuizControllerGetQuizzesAdmin400Code)[keyof typeof GetQuizControllerGetQuizzesAdmin400Code];

export const GetQuizControllerGetQuizzesAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type GetQuizControllerGetQuizzesAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizControllerGetQuizzesAdmin400Code;
};

/**
 * error code
 */
export type GetQuizControllerGetQuizzesAdmin401Code =
  (typeof GetQuizControllerGetQuizzesAdmin401Code)[keyof typeof GetQuizControllerGetQuizzesAdmin401Code];

export const GetQuizControllerGetQuizzesAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type GetQuizControllerGetQuizzesAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizControllerGetQuizzesAdmin401Code;
};

/**
 * error code
 */
export type GetQuizControllerGetQuizzesAdmin403Code =
  (typeof GetQuizControllerGetQuizzesAdmin403Code)[keyof typeof GetQuizControllerGetQuizzesAdmin403Code];

export const GetQuizControllerGetQuizzesAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type GetQuizControllerGetQuizzesAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizControllerGetQuizzesAdmin403Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin400Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin400Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin400Code];

export const UpdateQuizControllerUpdateQuizAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
  QUIZIMAGE_NOT_FOUND: 'QUIZ.IMAGE_NOT_FOUND',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin400Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin401Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin401Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin401Code];

export const UpdateQuizControllerUpdateQuizAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin401Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin403Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin403Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin403Code];

export const UpdateQuizControllerUpdateQuizAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin403Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin404Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin404Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin404Code];

export const UpdateQuizControllerUpdateQuizAdmin404Code = {
  QUIZNOT_FOUND: 'QUIZ.NOT_FOUND',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin404Code;
};
