/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
import type {
  CreateNicknameSourceDto,
  CreateQuizImageDto,
  CreateQuizzesDto,
  ListNicknameSourcesControllerListNicknameSourcesParams,
  ListQuizImagesControllerListQuizImagesAdminParams,
  NicknameSourceCollectionDto,
  NicknameSourceDto,
  QuizCollectionDto,
  QuizDto,
  QuizImageCollectionDto,
  QuizImageDto,
  UpdateNicknameSourceDto,
  UpdateQuizDto,
} from './quizzesGameIoBackend.schemas';

import { orvalInstance } from '../../../shared/service/api/client/index';

/**
 * @summary 닉네임 소스 생성
 */
export const createNicknameSourceControllerCreateNicknameSourceAdmin = (
  createNicknameSourceDto: CreateNicknameSourceDto
) => {
  return orvalInstance<NicknameSourceDto>({
    url: `/admin/nickname-sources`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createNicknameSourceDto,
  });
};

/**
 * @summary 닉네임 소스 리스트 조회
 */
export const listNicknameSourcesControllerListNicknameSources = (
  params?: ListNicknameSourcesControllerListNicknameSourcesParams
) => {
  return orvalInstance<NicknameSourceCollectionDto>({
    url: `/admin/nickname-sources`,
    method: 'GET',
    params,
  });
};

/**
 * @summary 닉네임 소스 삭제
 */
export const deleteNicknameSourceControllerDeleteNicknameSource = (
  nicknameSourceId: string
) => {
  return orvalInstance<void>({
    url: `/admin/nickname-sources/${nicknameSourceId}`,
    method: 'DELETE',
  });
};

/**
 * @summary 닉네임 소스 조회
 */
export const getNicknameSourceControllerGetNicknameSourceAdmin = (
  nicknameSourceId: string
) => {
  return orvalInstance<NicknameSourceDto>({
    url: `/admin/nickname-sources/${nicknameSourceId}`,
    method: 'GET',
  });
};

/**
 * @summary 닉네임 소스 수정
 */
export const updateNicknameSourceControllerUpdateNicknameSource = (
  nicknameSourceId: string,
  updateNicknameSourceDto: UpdateNicknameSourceDto
) => {
  return orvalInstance<NicknameSourceDto>({
    url: `/admin/nickname-sources/${nicknameSourceId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateNicknameSourceDto,
  });
};

/**
 * @summary 퀴즈 대량 생성
 */
export const createQuizzesControllerCreateQuizzesAdmin = (
  createQuizzesDto: CreateQuizzesDto[]
) => {
  return orvalInstance<QuizDto[]>({
    url: `/admin/quizzes`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: createQuizzesDto,
  });
};

/**
 * @summary 퀴즈 목록 조회
 */
export const listQuizzesControllerListQuizzes = () => {
  return orvalInstance<QuizCollectionDto>({
    url: `/admin/quizzes`,
    method: 'GET',
  });
};

/**
 * @summary 퀴즈 삭제
 */
export const deleteQuizControllerDeleteQuizAdmin = (quizId: string) => {
  return orvalInstance<void>({
    url: `/admin/quizzes/${quizId}`,
    method: 'DELETE',
  });
};

/**
 * @summary 퀴즈 단일 조회
 */
export const getQuizControllerGetQuizzesAdmin = (quizId: string) => {
  return orvalInstance<QuizDto>({
    url: `/admin/quizzes/${quizId}`,
    method: 'GET',
  });
};

/**
 * @summary 퀴즈 수정
 */
export const updateQuizControllerUpdateQuizAdmin = (
  quizId: string,
  updateQuizDto: UpdateQuizDto
) => {
  return orvalInstance<QuizDto>({
    url: `/admin/quizzes/${quizId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateQuizDto,
  });
};

/**
 * @summary 퀴즈 이미지 업로드
 */
export const createQuizImageControllerCreateQuizImageAdmin = (
  createQuizImageDto: CreateQuizImageDto
) => {
  const formData = new FormData();
  formData.append(`file`, createQuizImageDto.file);
  formData.append(`category`, createQuizImageDto.category);

  return orvalInstance<QuizImageDto>({
    url: `/admin/quiz-images`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
  });
};

/**
 * @summary 퀴즈 이미지 리스트 조회
 */
export const listQuizImagesControllerListQuizImagesAdmin = (
  params?: ListQuizImagesControllerListQuizImagesAdminParams
) => {
  return orvalInstance<QuizImageCollectionDto>({
    url: `/admin/quiz-images`,
    method: 'GET',
    params,
  });
};

/**
 * @summary 퀴즈 이미지 제거
 */
export const deleteQuizImageControllerDeleteQuizImage = (
  quizImageId: string
) => {
  return orvalInstance<void>({
    url: `/admin/quiz-images/${quizImageId}`,
    method: 'DELETE',
  });
};

export type CreateNicknameSourceControllerCreateNicknameSourceAdminResult =
  NonNullable<
    Awaited<
      ReturnType<typeof createNicknameSourceControllerCreateNicknameSourceAdmin>
    >
  >;
export type ListNicknameSourcesControllerListNicknameSourcesResult =
  NonNullable<
    Awaited<ReturnType<typeof listNicknameSourcesControllerListNicknameSources>>
  >;
export type DeleteNicknameSourceControllerDeleteNicknameSourceResult =
  NonNullable<
    Awaited<
      ReturnType<typeof deleteNicknameSourceControllerDeleteNicknameSource>
    >
  >;
export type GetNicknameSourceControllerGetNicknameSourceAdminResult =
  NonNullable<
    Awaited<
      ReturnType<typeof getNicknameSourceControllerGetNicknameSourceAdmin>
    >
  >;
export type UpdateNicknameSourceControllerUpdateNicknameSourceResult =
  NonNullable<
    Awaited<
      ReturnType<typeof updateNicknameSourceControllerUpdateNicknameSource>
    >
  >;
export type CreateQuizzesControllerCreateQuizzesAdminResult = NonNullable<
  Awaited<ReturnType<typeof createQuizzesControllerCreateQuizzesAdmin>>
>;
export type ListQuizzesControllerListQuizzesResult = NonNullable<
  Awaited<ReturnType<typeof listQuizzesControllerListQuizzes>>
>;
export type DeleteQuizControllerDeleteQuizAdminResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuizControllerDeleteQuizAdmin>>
>;
export type GetQuizControllerGetQuizzesAdminResult = NonNullable<
  Awaited<ReturnType<typeof getQuizControllerGetQuizzesAdmin>>
>;
export type UpdateQuizControllerUpdateQuizAdminResult = NonNullable<
  Awaited<ReturnType<typeof updateQuizControllerUpdateQuizAdmin>>
>;
export type CreateQuizImageControllerCreateQuizImageAdminResult = NonNullable<
  Awaited<ReturnType<typeof createQuizImageControllerCreateQuizImageAdmin>>
>;
export type ListQuizImagesControllerListQuizImagesAdminResult = NonNullable<
  Awaited<ReturnType<typeof listQuizImagesControllerListQuizImagesAdmin>>
>;
export type DeleteQuizImageControllerDeleteQuizImageResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuizImageControllerDeleteQuizImage>>
>;
