/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
import type {
  CreateImageDto,
  CreateNicknameSourceDto,
  CreateQuizzesDto,
  ImageCollectionDto,
  ImageDto,
  ListImagesControllerListImagesAdminParams,
  NicknameSourceDto,
  QuizCollectionDto,
  QuizDto,
  UpdateQuizDto,
} from './quizzesGameIoBackend.schemas';

import { orvalInstance } from '../../../shared/service/api/client/index';

/**
 * @summary 이미지 업로드
 */
export const createImageControllerCreateImageAdmin = (
  createImageDto: CreateImageDto
) => {
  const formData = new FormData();
  formData.append(`file`, createImageDto.file);
  formData.append(`category`, createImageDto.category);

  return orvalInstance<ImageDto>({
    url: `/admin/images`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
  });
};

/**
 * @summary 이미지 리스트 조회
 */
export const listImagesControllerListImagesAdmin = (
  params?: ListImagesControllerListImagesAdminParams
) => {
  return orvalInstance<ImageCollectionDto>({
    url: `/admin/images`,
    method: 'GET',
    params,
  });
};

/**
 * @summary 이미지 제거
 */
export const deleteImageControllerDeleteImage = (imageId: string) => {
  return orvalInstance<void>({
    url: `/admin/images/${imageId}`,
    method: 'DELETE',
  });
};

/**
 * @summary 닉네임 소스 생성
 */
export const createNicknameSourceControllerCreateNicknameSourceAdmin = (
  createNicknameSourceDto: CreateNicknameSourceDto
) => {
  return orvalInstance<NicknameSourceDto>({
    url: `/admin/nickname-sources`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createNicknameSourceDto,
  });
};

/**
 * @summary 퀴즈 대량 생성
 */
export const createQuizzesControllerCreateQuizzesAdmin = (
  createQuizzesDto: CreateQuizzesDto[]
) => {
  return orvalInstance<QuizDto[]>({
    url: `/admin/quizzes`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: createQuizzesDto,
  });
};

/**
 * @summary 퀴즈 목록 조회
 */
export const listQuizzesControllerListQuizzes = () => {
  return orvalInstance<QuizCollectionDto>({
    url: `/admin/quizzes`,
    method: 'GET',
  });
};

/**
 * @summary 퀴즈 삭제
 */
export const deleteQuizControllerDeleteQuizAdmin = (quizId: string) => {
  return orvalInstance<void>({
    url: `/admin/quizzes/${quizId}`,
    method: 'DELETE',
  });
};

/**
 * @summary 퀴즈 단일 조회
 */
export const getQuizControllerGetQuizzesAdmin = (quizId: string) => {
  return orvalInstance<QuizDto>({
    url: `/admin/quizzes/${quizId}`,
    method: 'GET',
  });
};

/**
 * @summary 퀴즈 수정
 */
export const updateQuizControllerUpdateQuizAdmin = (
  quizId: string,
  updateQuizDto: UpdateQuizDto
) => {
  return orvalInstance<QuizDto>({
    url: `/admin/quizzes/${quizId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateQuizDto,
  });
};

export type CreateImageControllerCreateImageAdminResult = NonNullable<
  Awaited<ReturnType<typeof createImageControllerCreateImageAdmin>>
>;
export type ListImagesControllerListImagesAdminResult = NonNullable<
  Awaited<ReturnType<typeof listImagesControllerListImagesAdmin>>
>;
export type DeleteImageControllerDeleteImageResult = NonNullable<
  Awaited<ReturnType<typeof deleteImageControllerDeleteImage>>
>;
export type CreateNicknameSourceControllerCreateNicknameSourceAdminResult =
  NonNullable<
    Awaited<
      ReturnType<typeof createNicknameSourceControllerCreateNicknameSourceAdmin>
    >
  >;
export type CreateQuizzesControllerCreateQuizzesAdminResult = NonNullable<
  Awaited<ReturnType<typeof createQuizzesControllerCreateQuizzesAdmin>>
>;
export type ListQuizzesControllerListQuizzesResult = NonNullable<
  Awaited<ReturnType<typeof listQuizzesControllerListQuizzes>>
>;
export type DeleteQuizControllerDeleteQuizAdminResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuizControllerDeleteQuizAdmin>>
>;
export type GetQuizControllerGetQuizzesAdminResult = NonNullable<
  Awaited<ReturnType<typeof getQuizControllerGetQuizzesAdmin>>
>;
export type UpdateQuizControllerUpdateQuizAdminResult = NonNullable<
  Awaited<ReturnType<typeof updateQuizControllerUpdateQuizAdmin>>
>;
