/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
export interface AccountDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Account role */
  role: string;
  /** Account sign in type */
  signInType: string;
  nickname: string;
  avatarFileName: string;
  avatarUrl: string;
  /** 진입 시점 */
  enteredAt: string;
  leftAt: string;
  isActive: boolean;
}

export interface ActiveAccountCountDto {
  count: number;
}

export interface AccountCollectionDto {
  data: AccountDto[];
}

export interface SignUpWithUsernameDto {
  username: string;
  password: string;
}

export interface AuthTokenDto {
  accessToken: string;
}

export interface SignInWithUsernameDto {
  username: string;
  password: string;
}

export interface CreateAvatarDto {
  file: Blob;
  /** @minLength 1 */
  name?: string;
  /** 아바타 설명 */
  description?: string;
}

/**
 * @nullable
 */
export type AvatarAdminDtoDescription = { [key: string]: unknown } | null;

export interface AvatarAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  originalFileName: string;
  avatarFileName: string;
  avatarImageUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  width: number;
  height: number;
  /** @nullable */
  description: AvatarAdminDtoDescription;
  usageCount: number;
}

export interface AvatarCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: AvatarAdminDto[];
}

export interface UpdateAvatarAdminDto {
  /** @minLength 1 */
  name?: string;
  /** @nullable */
  description?: string | null;
}

export interface CreateGameRoomDto {
  /**
   * 게임 방 제목
   * @minLength 1
   * @maxLength 50
   */
  title: string;
  /**
   * @minimum 10
   * @maximum 100
   */
  quizzesCount: number;
}

export type GameRoomMemberDtoRole =
  (typeof GameRoomMemberDtoRole)[keyof typeof GameRoomMemberDtoRole];

export const GameRoomMemberDtoRole = {
  host: 'host',
  player: 'player',
} as const;

export interface GameRoomMemberDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  gameRoomId: string;
  role: GameRoomMemberDtoRole;
  /** 게임방 구성원의 닉네임(계정 닉네임과 동일함) */
  nickname: string;
}

export type GameRoomDtoStatus =
  (typeof GameRoomDtoStatus)[keyof typeof GameRoomDtoStatus];

export const GameRoomDtoStatus = {
  waiting: 'waiting',
  starting: 'starting',
  inProgress: 'inProgress',
  finished: 'finished',
  paused: 'paused',
} as const;

export interface GameRoomDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  hostId: string;
  status: GameRoomDtoStatus;
  title: string;
  maxMembersCount: number;
  currentMembersCount: number;
  quizTimeLimitInSeconds: number;
  quizzesCount: number;
  members: GameRoomMemberDto[];
}

export interface GameRoomMemberCollectionDto {
  data: GameRoomMemberDto[];
}

export interface GameRoomCollectionDto {
  data: GameRoomDto[];
}

export interface CreateNicknameSourceAdminDto {
  /**
   * @minLength 1
   * @maxLength 10
   */
  name: string;
}

export interface NicknameSourceAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  sequence: number;
  fullname: string;
}

export interface NicknameSourceCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: NicknameSourceAdminDto[];
}

export interface UpdateNicknameSourceAdminDto {
  /**
   * @minLength 1
   * @maxLength 10
   */
  name?: string;
}

export interface CreateQuizzesAdminDto {
  type: string;
  answer: string;
  /** @nullable */
  question: string | null;
  /** @nullable */
  imageFileName: string | null;
}

export interface QuizAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** 퀴즈 유형 */
  type: string;
  /**
   * 퀴즈 질문
   * @nullable
   */
  question: string | null;
  /** 퀴즈 정답 */
  answer: string;
  /**
   * 퀴즈 이미지 파일명
   * @nullable
   */
  imageFileName: string | null;
  /**
   * 퀴즈 이미지 URL
   * @nullable
   */
  imageUrl: string | null;
}

export interface QuizCollectionAdminDto {
  data: QuizAdminDto[];
}

export interface UpdateQuizAdminDto {
  type?: string;
  answer?: string;
  /** @nullable */
  question?: string | null;
  /** @nullable */
  imageFileName?: string | null;
}

export interface CreateQuizImageAdminDto {
  /** quiz image file */
  file: Blob;
  /** quiz image category */
  category: string;
  /** @minLength 1 */
  name?: string;
}

export interface QuizImageAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  category: string;
  name: string;
  originalFileName: string;
  quizImageFileName: string;
  quizImageUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  width: number;
  height: number;
}

export interface QuizImageCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: QuizImageAdminDto[];
}

export interface UpdateQuizImageAdminDto {
  /** @minLength 1 */
  name?: string;
  category?: string;
}

export interface CreateSoundEffectDto {
  file: Blob;
  /** @minLength 1 */
  name?: string;
  description?: string;
}

/**
 * @nullable
 */
export type SoundEffectAdminDtoDescription = { [key: string]: unknown } | null;

export interface SoundEffectAdminDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  originalFileName: string;
  soundEffectFileName: string;
  soundEffectUrl: string;
  extension: string;
  contentType: string;
  contentLength: number;
  /** @nullable */
  description: SoundEffectAdminDtoDescription;
}

export interface SoundEffectCollectionAdminDto {
  currentPage: number;
  perPage: number;
  totalCount: number;
  totalPages: number;
  data: SoundEffectAdminDto[];
}

export interface UpdateSoundEffectAdminDto {
  /** @minLength 1 */
  name?: string;
  /** @nullable */
  description?: string | null;
}

/**
 * error code
 */
export type CreateAvatarControllerCreateAvatarAdmin400Code =
  (typeof CreateAvatarControllerCreateAvatarAdmin400Code)[keyof typeof CreateAvatarControllerCreateAvatarAdmin400Code];

export const CreateAvatarControllerCreateAvatarAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateAvatarControllerCreateAvatarAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateAvatarControllerCreateAvatarAdmin400Code;
};

/**
 * error code
 */
export type CreateAvatarControllerCreateAvatarAdmin401Code =
  (typeof CreateAvatarControllerCreateAvatarAdmin401Code)[keyof typeof CreateAvatarControllerCreateAvatarAdmin401Code];

export const CreateAvatarControllerCreateAvatarAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateAvatarControllerCreateAvatarAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateAvatarControllerCreateAvatarAdmin401Code;
};

/**
 * error code
 */
export type CreateAvatarControllerCreateAvatarAdmin403Code =
  (typeof CreateAvatarControllerCreateAvatarAdmin403Code)[keyof typeof CreateAvatarControllerCreateAvatarAdmin403Code];

export const CreateAvatarControllerCreateAvatarAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateAvatarControllerCreateAvatarAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateAvatarControllerCreateAvatarAdmin403Code;
};

export type ListAvatarsControllerListAvatarsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 5
 * @maximum 1000
 */
perPage?: number;
};

/**
 * error code
 */
export type ListAvatarsControllerListAvatars400Code = typeof ListAvatarsControllerListAvatars400Code[keyof typeof ListAvatarsControllerListAvatars400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAvatarsControllerListAvatars400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type ListAvatarsControllerListAvatars400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListAvatarsControllerListAvatars400Code;
};

/**
 * error code
 */
export type ListAvatarsControllerListAvatars401Code = typeof ListAvatarsControllerListAvatars401Code[keyof typeof ListAvatarsControllerListAvatars401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAvatarsControllerListAvatars401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type ListAvatarsControllerListAvatars401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListAvatarsControllerListAvatars401Code;
};

/**
 * error code
 */
export type ListAvatarsControllerListAvatars403Code = typeof ListAvatarsControllerListAvatars403Code[keyof typeof ListAvatarsControllerListAvatars403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAvatarsControllerListAvatars403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type ListAvatarsControllerListAvatars403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListAvatarsControllerListAvatars403Code;
};

/**
 * error code
 */
export type GetAvatarControllerGetAvatar400Code = typeof GetAvatarControllerGetAvatar400Code[keyof typeof GetAvatarControllerGetAvatar400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAvatarControllerGetAvatar400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type GetAvatarControllerGetAvatar400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetAvatarControllerGetAvatar400Code;
};

/**
 * error code
 */
export type GetAvatarControllerGetAvatar401Code = typeof GetAvatarControllerGetAvatar401Code[keyof typeof GetAvatarControllerGetAvatar401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAvatarControllerGetAvatar401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type GetAvatarControllerGetAvatar401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetAvatarControllerGetAvatar401Code;
};

/**
 * error code
 */
export type GetAvatarControllerGetAvatar403Code = typeof GetAvatarControllerGetAvatar403Code[keyof typeof GetAvatarControllerGetAvatar403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAvatarControllerGetAvatar403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type GetAvatarControllerGetAvatar403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetAvatarControllerGetAvatar403Code;
};

/**
 * error code
 */
export type GetAvatarControllerGetAvatar404Code = typeof GetAvatarControllerGetAvatar404Code[keyof typeof GetAvatarControllerGetAvatar404Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAvatarControllerGetAvatar404Code = {
  AVATARNOT_FOUND: 'AVATAR.NOT_FOUND',
} as const;

export type GetAvatarControllerGetAvatar404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetAvatarControllerGetAvatar404Code;
};

/**
 * error code
 */
export type UpdateAvatarControllerUpdateAvatar400Code = typeof UpdateAvatarControllerUpdateAvatar400Code[keyof typeof UpdateAvatarControllerUpdateAvatar400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAvatarControllerUpdateAvatar400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type UpdateAvatarControllerUpdateAvatar400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateAvatarControllerUpdateAvatar400Code;
};

/**
 * error code
 */
export type UpdateAvatarControllerUpdateAvatar401Code = typeof UpdateAvatarControllerUpdateAvatar401Code[keyof typeof UpdateAvatarControllerUpdateAvatar401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAvatarControllerUpdateAvatar401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type UpdateAvatarControllerUpdateAvatar401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateAvatarControllerUpdateAvatar401Code;
};

/**
 * error code
 */
export type UpdateAvatarControllerUpdateAvatar403Code = typeof UpdateAvatarControllerUpdateAvatar403Code[keyof typeof UpdateAvatarControllerUpdateAvatar403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAvatarControllerUpdateAvatar403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type UpdateAvatarControllerUpdateAvatar403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateAvatarControllerUpdateAvatar403Code;
};

/**
 * error code
 */
export type UpdateAvatarControllerUpdateAvatar404Code = typeof UpdateAvatarControllerUpdateAvatar404Code[keyof typeof UpdateAvatarControllerUpdateAvatar404Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAvatarControllerUpdateAvatar404Code = {
  AVATARNOT_FOUND: 'AVATAR.NOT_FOUND',
} as const;

export type UpdateAvatarControllerUpdateAvatar404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateAvatarControllerUpdateAvatar404Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin400Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin401Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin403Code;
};

/**
 * error code
 */
export type CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code =
  (typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code)[keyof typeof CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code];

export const CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code = {
  NICKNAME_SOURCEALREADY_EXISTS: 'NICKNAME_SOURCE.ALREADY_EXISTS',
} as const;

export type CreateNicknameSourceControllerCreateNicknameSourceAdmin409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateNicknameSourceControllerCreateNicknameSourceAdmin409Code;
};

export type ListNicknameSourcesControllerListNicknameSourcesParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 5
   * @maximum 1000
   */
  perPage?: number;
};

/**
 * error code
 */
export type ListNicknameSourcesControllerListNicknameSources400Code =
  (typeof ListNicknameSourcesControllerListNicknameSources400Code)[keyof typeof ListNicknameSourcesControllerListNicknameSources400Code];

export const ListNicknameSourcesControllerListNicknameSources400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type ListNicknameSourcesControllerListNicknameSources400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListNicknameSourcesControllerListNicknameSources400Code;
};

/**
 * error code
 */
export type ListNicknameSourcesControllerListNicknameSources401Code =
  (typeof ListNicknameSourcesControllerListNicknameSources401Code)[keyof typeof ListNicknameSourcesControllerListNicknameSources401Code];

export const ListNicknameSourcesControllerListNicknameSources401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type ListNicknameSourcesControllerListNicknameSources401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListNicknameSourcesControllerListNicknameSources401Code;
};

/**
 * error code
 */
export type ListNicknameSourcesControllerListNicknameSources403Code =
  (typeof ListNicknameSourcesControllerListNicknameSources403Code)[keyof typeof ListNicknameSourcesControllerListNicknameSources403Code];

export const ListNicknameSourcesControllerListNicknameSources403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type ListNicknameSourcesControllerListNicknameSources403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListNicknameSourcesControllerListNicknameSources403Code;
};

/**
 * error code
 */
export type DeleteNicknameSourceControllerDeleteNicknameSource400Code =
  (typeof DeleteNicknameSourceControllerDeleteNicknameSource400Code)[keyof typeof DeleteNicknameSourceControllerDeleteNicknameSource400Code];

export const DeleteNicknameSourceControllerDeleteNicknameSource400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type DeleteNicknameSourceControllerDeleteNicknameSource400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteNicknameSourceControllerDeleteNicknameSource400Code;
};

/**
 * error code
 */
export type DeleteNicknameSourceControllerDeleteNicknameSource401Code =
  (typeof DeleteNicknameSourceControllerDeleteNicknameSource401Code)[keyof typeof DeleteNicknameSourceControllerDeleteNicknameSource401Code];

export const DeleteNicknameSourceControllerDeleteNicknameSource401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type DeleteNicknameSourceControllerDeleteNicknameSource401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteNicknameSourceControllerDeleteNicknameSource401Code;
};

/**
 * error code
 */
export type DeleteNicknameSourceControllerDeleteNicknameSource403Code =
  (typeof DeleteNicknameSourceControllerDeleteNicknameSource403Code)[keyof typeof DeleteNicknameSourceControllerDeleteNicknameSource403Code];

export const DeleteNicknameSourceControllerDeleteNicknameSource403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type DeleteNicknameSourceControllerDeleteNicknameSource403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteNicknameSourceControllerDeleteNicknameSource403Code;
};

/**
 * error code
 */
export type DeleteNicknameSourceControllerDeleteNicknameSource404Code =
  (typeof DeleteNicknameSourceControllerDeleteNicknameSource404Code)[keyof typeof DeleteNicknameSourceControllerDeleteNicknameSource404Code];

export const DeleteNicknameSourceControllerDeleteNicknameSource404Code = {
  NICKNAME_SOURCENOT_FOUND: 'NICKNAME_SOURCE.NOT_FOUND',
} as const;

export type DeleteNicknameSourceControllerDeleteNicknameSource404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteNicknameSourceControllerDeleteNicknameSource404Code;
};

/**
 * error code
 */
export type GetNicknameSourceControllerGetNicknameSourceAdmin400Code =
  (typeof GetNicknameSourceControllerGetNicknameSourceAdmin400Code)[keyof typeof GetNicknameSourceControllerGetNicknameSourceAdmin400Code];

export const GetNicknameSourceControllerGetNicknameSourceAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type GetNicknameSourceControllerGetNicknameSourceAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetNicknameSourceControllerGetNicknameSourceAdmin400Code;
};

/**
 * error code
 */
export type GetNicknameSourceControllerGetNicknameSourceAdmin401Code =
  (typeof GetNicknameSourceControllerGetNicknameSourceAdmin401Code)[keyof typeof GetNicknameSourceControllerGetNicknameSourceAdmin401Code];

export const GetNicknameSourceControllerGetNicknameSourceAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type GetNicknameSourceControllerGetNicknameSourceAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetNicknameSourceControllerGetNicknameSourceAdmin401Code;
};

/**
 * error code
 */
export type GetNicknameSourceControllerGetNicknameSourceAdmin403Code =
  (typeof GetNicknameSourceControllerGetNicknameSourceAdmin403Code)[keyof typeof GetNicknameSourceControllerGetNicknameSourceAdmin403Code];

export const GetNicknameSourceControllerGetNicknameSourceAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type GetNicknameSourceControllerGetNicknameSourceAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetNicknameSourceControllerGetNicknameSourceAdmin403Code;
};

/**
 * error code
 */
export type GetNicknameSourceControllerGetNicknameSourceAdmin404Code =
  (typeof GetNicknameSourceControllerGetNicknameSourceAdmin404Code)[keyof typeof GetNicknameSourceControllerGetNicknameSourceAdmin404Code];

export const GetNicknameSourceControllerGetNicknameSourceAdmin404Code = {
  NICKNAME_SOURCENOT_FOUND: 'NICKNAME_SOURCE.NOT_FOUND',
} as const;

export type GetNicknameSourceControllerGetNicknameSourceAdmin404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetNicknameSourceControllerGetNicknameSourceAdmin404Code;
};

/**
 * error code
 */
export type UpdateNicknameSourceControllerUpdateNicknameSource400Code =
  (typeof UpdateNicknameSourceControllerUpdateNicknameSource400Code)[keyof typeof UpdateNicknameSourceControllerUpdateNicknameSource400Code];

export const UpdateNicknameSourceControllerUpdateNicknameSource400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type UpdateNicknameSourceControllerUpdateNicknameSource400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateNicknameSourceControllerUpdateNicknameSource400Code;
};

/**
 * error code
 */
export type UpdateNicknameSourceControllerUpdateNicknameSource401Code =
  (typeof UpdateNicknameSourceControllerUpdateNicknameSource401Code)[keyof typeof UpdateNicknameSourceControllerUpdateNicknameSource401Code];

export const UpdateNicknameSourceControllerUpdateNicknameSource401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type UpdateNicknameSourceControllerUpdateNicknameSource401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateNicknameSourceControllerUpdateNicknameSource401Code;
};

/**
 * error code
 */
export type UpdateNicknameSourceControllerUpdateNicknameSource403Code =
  (typeof UpdateNicknameSourceControllerUpdateNicknameSource403Code)[keyof typeof UpdateNicknameSourceControllerUpdateNicknameSource403Code];

export const UpdateNicknameSourceControllerUpdateNicknameSource403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type UpdateNicknameSourceControllerUpdateNicknameSource403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateNicknameSourceControllerUpdateNicknameSource403Code;
};

/**
 * error code
 */
export type UpdateNicknameSourceControllerUpdateNicknameSource404Code =
  (typeof UpdateNicknameSourceControllerUpdateNicknameSource404Code)[keyof typeof UpdateNicknameSourceControllerUpdateNicknameSource404Code];

export const UpdateNicknameSourceControllerUpdateNicknameSource404Code = {
  NICKNAME_SOURCENOT_FOUND: 'NICKNAME_SOURCE.NOT_FOUND',
} as const;

export type UpdateNicknameSourceControllerUpdateNicknameSource404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateNicknameSourceControllerUpdateNicknameSource404Code;
};

/**
 * error code
 */
export type UpdateNicknameSourceControllerUpdateNicknameSource409Code =
  (typeof UpdateNicknameSourceControllerUpdateNicknameSource409Code)[keyof typeof UpdateNicknameSourceControllerUpdateNicknameSource409Code];

export const UpdateNicknameSourceControllerUpdateNicknameSource409Code = {
  NICKNAME_SOURCEALREADY_EXISTS: 'NICKNAME_SOURCE.ALREADY_EXISTS',
} as const;

export type UpdateNicknameSourceControllerUpdateNicknameSource409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateNicknameSourceControllerUpdateNicknameSource409Code;
};

/**
 * error code
 */
export type CreateQuizzesControllerCreateQuizzesAdmin400Code =
  (typeof CreateQuizzesControllerCreateQuizzesAdmin400Code)[keyof typeof CreateQuizzesControllerCreateQuizzesAdmin400Code];

export const CreateQuizzesControllerCreateQuizzesAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateQuizzesControllerCreateQuizzesAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizzesControllerCreateQuizzesAdmin400Code;
};

/**
 * error code
 */
export type CreateQuizzesControllerCreateQuizzesAdmin401Code =
  (typeof CreateQuizzesControllerCreateQuizzesAdmin401Code)[keyof typeof CreateQuizzesControllerCreateQuizzesAdmin401Code];

export const CreateQuizzesControllerCreateQuizzesAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateQuizzesControllerCreateQuizzesAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizzesControllerCreateQuizzesAdmin401Code;
};

/**
 * error code
 */
export type CreateQuizzesControllerCreateQuizzesAdmin403Code =
  (typeof CreateQuizzesControllerCreateQuizzesAdmin403Code)[keyof typeof CreateQuizzesControllerCreateQuizzesAdmin403Code];

export const CreateQuizzesControllerCreateQuizzesAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateQuizzesControllerCreateQuizzesAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizzesControllerCreateQuizzesAdmin403Code;
};

export type ListQuizzesControllerListQuizzesParams = {
  /**
   * 이미지 파일 이름으로 필터링
   */
  imageFileName?: string;
};

/**
 * error code
 */
export type ListQuizzesControllerListQuizzes400Code =
  (typeof ListQuizzesControllerListQuizzes400Code)[keyof typeof ListQuizzesControllerListQuizzes400Code];

export const ListQuizzesControllerListQuizzes400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type ListQuizzesControllerListQuizzes400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizzesControllerListQuizzes400Code;
};

/**
 * error code
 */
export type ListQuizzesControllerListQuizzes401Code =
  (typeof ListQuizzesControllerListQuizzes401Code)[keyof typeof ListQuizzesControllerListQuizzes401Code];

export const ListQuizzesControllerListQuizzes401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type ListQuizzesControllerListQuizzes401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizzesControllerListQuizzes401Code;
};

/**
 * error code
 */
export type ListQuizzesControllerListQuizzes403Code =
  (typeof ListQuizzesControllerListQuizzes403Code)[keyof typeof ListQuizzesControllerListQuizzes403Code];

export const ListQuizzesControllerListQuizzes403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type ListQuizzesControllerListQuizzes403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizzesControllerListQuizzes403Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin400Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin400Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin400Code];

export const DeleteQuizControllerDeleteQuizAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin400Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin401Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin401Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin401Code];

export const DeleteQuizControllerDeleteQuizAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin401Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin403Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin403Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin403Code];

export const DeleteQuizControllerDeleteQuizAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin403Code;
};

/**
 * error code
 */
export type DeleteQuizControllerDeleteQuizAdmin404Code =
  (typeof DeleteQuizControllerDeleteQuizAdmin404Code)[keyof typeof DeleteQuizControllerDeleteQuizAdmin404Code];

export const DeleteQuizControllerDeleteQuizAdmin404Code = {
  QUIZNOT_FOUND: 'QUIZ.NOT_FOUND',
} as const;

export type DeleteQuizControllerDeleteQuizAdmin404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizControllerDeleteQuizAdmin404Code;
};

/**
 * error code
 */
export type GetQuizControllerGetQuizzesAdmin400Code =
  (typeof GetQuizControllerGetQuizzesAdmin400Code)[keyof typeof GetQuizControllerGetQuizzesAdmin400Code];

export const GetQuizControllerGetQuizzesAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type GetQuizControllerGetQuizzesAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizControllerGetQuizzesAdmin400Code;
};

/**
 * error code
 */
export type GetQuizControllerGetQuizzesAdmin401Code =
  (typeof GetQuizControllerGetQuizzesAdmin401Code)[keyof typeof GetQuizControllerGetQuizzesAdmin401Code];

export const GetQuizControllerGetQuizzesAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type GetQuizControllerGetQuizzesAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizControllerGetQuizzesAdmin401Code;
};

/**
 * error code
 */
export type GetQuizControllerGetQuizzesAdmin403Code =
  (typeof GetQuizControllerGetQuizzesAdmin403Code)[keyof typeof GetQuizControllerGetQuizzesAdmin403Code];

export const GetQuizControllerGetQuizzesAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type GetQuizControllerGetQuizzesAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizControllerGetQuizzesAdmin403Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin400Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin400Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin400Code];

export const UpdateQuizControllerUpdateQuizAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
  QUIZIMAGE_NOT_FOUND: 'QUIZ.IMAGE_NOT_FOUND',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin400Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin401Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin401Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin401Code];

export const UpdateQuizControllerUpdateQuizAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin401Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin403Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin403Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin403Code];

export const UpdateQuizControllerUpdateQuizAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin403Code;
};

/**
 * error code
 */
export type UpdateQuizControllerUpdateQuizAdmin404Code =
  (typeof UpdateQuizControllerUpdateQuizAdmin404Code)[keyof typeof UpdateQuizControllerUpdateQuizAdmin404Code];

export const UpdateQuizControllerUpdateQuizAdmin404Code = {
  QUIZNOT_FOUND: 'QUIZ.NOT_FOUND',
} as const;

export type UpdateQuizControllerUpdateQuizAdmin404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizControllerUpdateQuizAdmin404Code;
};

/**
 * error code
 */
export type CreateQuizImageControllerCreateQuizImageAdmin400Code =
  (typeof CreateQuizImageControllerCreateQuizImageAdmin400Code)[keyof typeof CreateQuizImageControllerCreateQuizImageAdmin400Code];

export const CreateQuizImageControllerCreateQuizImageAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateQuizImageControllerCreateQuizImageAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizImageControllerCreateQuizImageAdmin400Code;
};

/**
 * error code
 */
export type CreateQuizImageControllerCreateQuizImageAdmin401Code =
  (typeof CreateQuizImageControllerCreateQuizImageAdmin401Code)[keyof typeof CreateQuizImageControllerCreateQuizImageAdmin401Code];

export const CreateQuizImageControllerCreateQuizImageAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateQuizImageControllerCreateQuizImageAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizImageControllerCreateQuizImageAdmin401Code;
};

/**
 * error code
 */
export type CreateQuizImageControllerCreateQuizImageAdmin403Code =
  (typeof CreateQuizImageControllerCreateQuizImageAdmin403Code)[keyof typeof CreateQuizImageControllerCreateQuizImageAdmin403Code];

export const CreateQuizImageControllerCreateQuizImageAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateQuizImageControllerCreateQuizImageAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateQuizImageControllerCreateQuizImageAdmin403Code;
};

export type ListQuizImagesControllerListQuizImagesAdminParams = {
  /**
   * 카테고리 필터링
   */
  category?: string;
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 5
   * @maximum 1000
   */
  perPage?: number;
  /**
 * 
    정렬 쿼리. 다중 정렬은 콤마(,)로 구분.
    허용되지 않은 정렬 필드 및 방향은 무시합니다.
    형식: field:asc | field:desc
    허용 필드: createdAt,updatedAt,name,category,
    예: sort=-title:asc,createdAt:asc
      
 */
  sort?: string;
};

/**
 * error code
 */
export type ListQuizImagesControllerListQuizImagesAdmin400Code =
  (typeof ListQuizImagesControllerListQuizImagesAdmin400Code)[keyof typeof ListQuizImagesControllerListQuizImagesAdmin400Code];

export const ListQuizImagesControllerListQuizImagesAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type ListQuizImagesControllerListQuizImagesAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizImagesControllerListQuizImagesAdmin400Code;
};

/**
 * error code
 */
export type ListQuizImagesControllerListQuizImagesAdmin401Code =
  (typeof ListQuizImagesControllerListQuizImagesAdmin401Code)[keyof typeof ListQuizImagesControllerListQuizImagesAdmin401Code];

export const ListQuizImagesControllerListQuizImagesAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type ListQuizImagesControllerListQuizImagesAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizImagesControllerListQuizImagesAdmin401Code;
};

/**
 * error code
 */
export type ListQuizImagesControllerListQuizImagesAdmin403Code =
  (typeof ListQuizImagesControllerListQuizImagesAdmin403Code)[keyof typeof ListQuizImagesControllerListQuizImagesAdmin403Code];

export const ListQuizImagesControllerListQuizImagesAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type ListQuizImagesControllerListQuizImagesAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListQuizImagesControllerListQuizImagesAdmin403Code;
};

/**
 * error code
 */
export type DeleteQuizImageControllerDeleteQuizImage400Code =
  (typeof DeleteQuizImageControllerDeleteQuizImage400Code)[keyof typeof DeleteQuizImageControllerDeleteQuizImage400Code];

export const DeleteQuizImageControllerDeleteQuizImage400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type DeleteQuizImageControllerDeleteQuizImage400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizImageControllerDeleteQuizImage400Code;
};

/**
 * error code
 */
export type DeleteQuizImageControllerDeleteQuizImage401Code =
  (typeof DeleteQuizImageControllerDeleteQuizImage401Code)[keyof typeof DeleteQuizImageControllerDeleteQuizImage401Code];

export const DeleteQuizImageControllerDeleteQuizImage401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type DeleteQuizImageControllerDeleteQuizImage401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizImageControllerDeleteQuizImage401Code;
};

/**
 * error code
 */
export type DeleteQuizImageControllerDeleteQuizImage403Code =
  (typeof DeleteQuizImageControllerDeleteQuizImage403Code)[keyof typeof DeleteQuizImageControllerDeleteQuizImage403Code];

export const DeleteQuizImageControllerDeleteQuizImage403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type DeleteQuizImageControllerDeleteQuizImage403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizImageControllerDeleteQuizImage403Code;
};

/**
 * error code
 */
export type DeleteQuizImageControllerDeleteQuizImage404Code =
  (typeof DeleteQuizImageControllerDeleteQuizImage404Code)[keyof typeof DeleteQuizImageControllerDeleteQuizImage404Code];

export const DeleteQuizImageControllerDeleteQuizImage404Code = {
  QUIZ_IMAGENOT_FOUND: 'QUIZ_IMAGE.NOT_FOUND',
} as const;

export type DeleteQuizImageControllerDeleteQuizImage404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizImageControllerDeleteQuizImage404Code;
};

/**
 * error code
 */
export type DeleteQuizImageControllerDeleteQuizImage409Code =
  (typeof DeleteQuizImageControllerDeleteQuizImage409Code)[keyof typeof DeleteQuizImageControllerDeleteQuizImage409Code];

export const DeleteQuizImageControllerDeleteQuizImage409Code = {
  QUIZ_IMAGEIN_USED: 'QUIZ_IMAGE.IN_USED',
} as const;

export type DeleteQuizImageControllerDeleteQuizImage409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: DeleteQuizImageControllerDeleteQuizImage409Code;
};

/**
 * error code
 */
export type GetQuizImageControllerGetQuizImage400Code =
  (typeof GetQuizImageControllerGetQuizImage400Code)[keyof typeof GetQuizImageControllerGetQuizImage400Code];

export const GetQuizImageControllerGetQuizImage400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type GetQuizImageControllerGetQuizImage400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizImageControllerGetQuizImage400Code;
};

/**
 * error code
 */
export type GetQuizImageControllerGetQuizImage401Code =
  (typeof GetQuizImageControllerGetQuizImage401Code)[keyof typeof GetQuizImageControllerGetQuizImage401Code];

export const GetQuizImageControllerGetQuizImage401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type GetQuizImageControllerGetQuizImage401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizImageControllerGetQuizImage401Code;
};

/**
 * error code
 */
export type GetQuizImageControllerGetQuizImage403Code =
  (typeof GetQuizImageControllerGetQuizImage403Code)[keyof typeof GetQuizImageControllerGetQuizImage403Code];

export const GetQuizImageControllerGetQuizImage403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type GetQuizImageControllerGetQuizImage403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizImageControllerGetQuizImage403Code;
};

/**
 * error code
 */
export type GetQuizImageControllerGetQuizImage404Code =
  (typeof GetQuizImageControllerGetQuizImage404Code)[keyof typeof GetQuizImageControllerGetQuizImage404Code];

export const GetQuizImageControllerGetQuizImage404Code = {
  QUIZ_IMAGENOT_FOUND: 'QUIZ_IMAGE.NOT_FOUND',
} as const;

export type GetQuizImageControllerGetQuizImage404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetQuizImageControllerGetQuizImage404Code;
};

/**
 * error code
 */
export type UpdateQuizImageControllerUpdateQuizImageAdmin400Code = typeof UpdateQuizImageControllerUpdateQuizImageAdmin400Code[keyof typeof UpdateQuizImageControllerUpdateQuizImageAdmin400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateQuizImageControllerUpdateQuizImageAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type UpdateQuizImageControllerUpdateQuizImageAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizImageControllerUpdateQuizImageAdmin400Code;
};

/**
 * error code
 */
export type UpdateQuizImageControllerUpdateQuizImageAdmin401Code = typeof UpdateQuizImageControllerUpdateQuizImageAdmin401Code[keyof typeof UpdateQuizImageControllerUpdateQuizImageAdmin401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateQuizImageControllerUpdateQuizImageAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type UpdateQuizImageControllerUpdateQuizImageAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizImageControllerUpdateQuizImageAdmin401Code;
};

/**
 * error code
 */
export type UpdateQuizImageControllerUpdateQuizImageAdmin403Code = typeof UpdateQuizImageControllerUpdateQuizImageAdmin403Code[keyof typeof UpdateQuizImageControllerUpdateQuizImageAdmin403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateQuizImageControllerUpdateQuizImageAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type UpdateQuizImageControllerUpdateQuizImageAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizImageControllerUpdateQuizImageAdmin403Code;
};

/**
 * error code
 */
export type UpdateQuizImageControllerUpdateQuizImageAdmin404Code = typeof UpdateQuizImageControllerUpdateQuizImageAdmin404Code[keyof typeof UpdateQuizImageControllerUpdateQuizImageAdmin404Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateQuizImageControllerUpdateQuizImageAdmin404Code = {
  QUIZ_IMAGENOT_FOUND: 'QUIZ_IMAGE.NOT_FOUND',
} as const;

export type UpdateQuizImageControllerUpdateQuizImageAdmin404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateQuizImageControllerUpdateQuizImageAdmin404Code;
};

/**
 * error code
 */
export type CreateSoundEffectControllerCreateSoundEffectAdmin400Code = typeof CreateSoundEffectControllerCreateSoundEffectAdmin400Code[keyof typeof CreateSoundEffectControllerCreateSoundEffectAdmin400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSoundEffectControllerCreateSoundEffectAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type CreateSoundEffectControllerCreateSoundEffectAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateSoundEffectControllerCreateSoundEffectAdmin400Code;
};

/**
 * error code
 */
export type CreateSoundEffectControllerCreateSoundEffectAdmin401Code = typeof CreateSoundEffectControllerCreateSoundEffectAdmin401Code[keyof typeof CreateSoundEffectControllerCreateSoundEffectAdmin401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSoundEffectControllerCreateSoundEffectAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type CreateSoundEffectControllerCreateSoundEffectAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateSoundEffectControllerCreateSoundEffectAdmin401Code;
};

/**
 * error code
 */
export type CreateSoundEffectControllerCreateSoundEffectAdmin403Code = typeof CreateSoundEffectControllerCreateSoundEffectAdmin403Code[keyof typeof CreateSoundEffectControllerCreateSoundEffectAdmin403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSoundEffectControllerCreateSoundEffectAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type CreateSoundEffectControllerCreateSoundEffectAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateSoundEffectControllerCreateSoundEffectAdmin403Code;
};

export type ListSoundEffectsControllerListSoundEffectsAdminParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 5
 * @maximum 1000
 */
perPage?: number;
};

/**
 * error code
 */
export type ListSoundEffectsControllerListSoundEffectsAdmin400Code = typeof ListSoundEffectsControllerListSoundEffectsAdmin400Code[keyof typeof ListSoundEffectsControllerListSoundEffectsAdmin400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListSoundEffectsControllerListSoundEffectsAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type ListSoundEffectsControllerListSoundEffectsAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListSoundEffectsControllerListSoundEffectsAdmin400Code;
};

/**
 * error code
 */
export type ListSoundEffectsControllerListSoundEffectsAdmin401Code = typeof ListSoundEffectsControllerListSoundEffectsAdmin401Code[keyof typeof ListSoundEffectsControllerListSoundEffectsAdmin401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListSoundEffectsControllerListSoundEffectsAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type ListSoundEffectsControllerListSoundEffectsAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListSoundEffectsControllerListSoundEffectsAdmin401Code;
};

/**
 * error code
 */
export type ListSoundEffectsControllerListSoundEffectsAdmin403Code = typeof ListSoundEffectsControllerListSoundEffectsAdmin403Code[keyof typeof ListSoundEffectsControllerListSoundEffectsAdmin403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListSoundEffectsControllerListSoundEffectsAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type ListSoundEffectsControllerListSoundEffectsAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListSoundEffectsControllerListSoundEffectsAdmin403Code;
};

/**
 * error code
 */
export type GetSoundEffectControllerGetSoundEffect400Code = typeof GetSoundEffectControllerGetSoundEffect400Code[keyof typeof GetSoundEffectControllerGetSoundEffect400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSoundEffectControllerGetSoundEffect400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type GetSoundEffectControllerGetSoundEffect400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetSoundEffectControllerGetSoundEffect400Code;
};

/**
 * error code
 */
export type GetSoundEffectControllerGetSoundEffect401Code = typeof GetSoundEffectControllerGetSoundEffect401Code[keyof typeof GetSoundEffectControllerGetSoundEffect401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSoundEffectControllerGetSoundEffect401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type GetSoundEffectControllerGetSoundEffect401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetSoundEffectControllerGetSoundEffect401Code;
};

/**
 * error code
 */
export type GetSoundEffectControllerGetSoundEffect403Code = typeof GetSoundEffectControllerGetSoundEffect403Code[keyof typeof GetSoundEffectControllerGetSoundEffect403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSoundEffectControllerGetSoundEffect403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type GetSoundEffectControllerGetSoundEffect403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetSoundEffectControllerGetSoundEffect403Code;
};

/**
 * error code
 */
export type GetSoundEffectControllerGetSoundEffect404Code = typeof GetSoundEffectControllerGetSoundEffect404Code[keyof typeof GetSoundEffectControllerGetSoundEffect404Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSoundEffectControllerGetSoundEffect404Code = {
  SOUND_EFFECTNOT_FOUND: 'SOUND_EFFECT.NOT_FOUND',
} as const;

export type GetSoundEffectControllerGetSoundEffect404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: GetSoundEffectControllerGetSoundEffect404Code;
};

/**
 * error code
 */
export type UpdateSoundEffectControllerUpdateSoundEffectAdmin400Code = typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin400Code[keyof typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSoundEffectControllerUpdateSoundEffectAdmin400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;

export type UpdateSoundEffectControllerUpdateSoundEffectAdmin400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateSoundEffectControllerUpdateSoundEffectAdmin400Code;
};

/**
 * error code
 */
export type UpdateSoundEffectControllerUpdateSoundEffectAdmin401Code = typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin401Code[keyof typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSoundEffectControllerUpdateSoundEffectAdmin401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;

export type UpdateSoundEffectControllerUpdateSoundEffectAdmin401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateSoundEffectControllerUpdateSoundEffectAdmin401Code;
};

/**
 * error code
 */
export type UpdateSoundEffectControllerUpdateSoundEffectAdmin403Code = typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin403Code[keyof typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSoundEffectControllerUpdateSoundEffectAdmin403Code = {
  COMMONPERMISSION_DENIED: 'COMMON.PERMISSION_DENIED',
} as const;

export type UpdateSoundEffectControllerUpdateSoundEffectAdmin403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateSoundEffectControllerUpdateSoundEffectAdmin403Code;
};

/**
 * error code
 */
export type UpdateSoundEffectControllerUpdateSoundEffectAdmin404Code = typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin404Code[keyof typeof UpdateSoundEffectControllerUpdateSoundEffectAdmin404Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSoundEffectControllerUpdateSoundEffectAdmin404Code = {
  SOUND_EFFECTNOT_FOUND: 'SOUND_EFFECT.NOT_FOUND',
} as const;

export type UpdateSoundEffectControllerUpdateSoundEffectAdmin404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: UpdateSoundEffectControllerUpdateSoundEffectAdmin404Code;
};
