/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
import type {
  AccountCollectionAdminDto,
  AvatarAdminDto,
  AvatarCollectionAdminDto,
  CreateAvatarDto,
  CreateNicknameSourceAdminDto,
  CreateQuizImageAdminDto,
  CreateQuizzesAdminDto,
  CreateSoundEffectDto,
  ListAccountsControllerListAccountsAdminParams,
  ListAvatarsControllerListAvatarsParams,
  ListNicknameSourcesControllerListNicknameSourcesParams,
  ListQuizImagesControllerListQuizImagesAdminParams,
  ListQuizzesControllerListQuizzesParams,
  ListSoundEffectsControllerListSoundEffectsAdminParams,
  NicknameSourceAdminDto,
  NicknameSourceCollectionAdminDto,
  QuizAdminDto,
  QuizCollectionAdminDto,
  QuizImageAdminDto,
  QuizImageCollectionAdminDto,
  SoundEffectAdminDto,
  SoundEffectCollectionAdminDto,
  UpdateAvatarAdminDto,
  UpdateNicknameSourceAdminDto,
  UpdateQuizAdminDto,
  UpdateQuizImageAdminDto,
  UpdateSoundEffectAdminDto
} from './quizzesGameIoBackend.schemas';

import { orvalInstance } from '../../../shared/service/api/client/index';



  /**
 * @summary 계정 목록 조회
 */
export const listAccountsControllerListAccountsAdmin = (
    params?: ListAccountsControllerListAccountsAdminParams,
 ) => {
      return orvalInstance<AccountCollectionAdminDto>(
      {url: `/admin/accounts`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 아바타 생성
 */
export const createAvatarControllerCreateAvatarAdmin = (
    createAvatarDto: CreateAvatarDto,
 ) => {const formData = new FormData();
formData.append(`file`, createAvatarDto.file)
if(createAvatarDto.name !== undefined) {
 formData.append(`name`, createAvatarDto.name)
 }
if(createAvatarDto.description !== undefined) {
 formData.append(`description`, createAvatarDto.description)
 }

      return orvalInstance<AvatarAdminDto>(
      {url: `/admin/avatars`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * @summary 아바타 리스트 조회
 */
export const listAvatarsControllerListAvatars = (
    params?: ListAvatarsControllerListAvatarsParams,
 ) => {
      return orvalInstance<AvatarCollectionAdminDto>(
      {url: `/admin/avatars`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 아바타 삭제
 */
export const deleteAvatarControllerDeleteAvatarAdmin = (
    avatarId: string,
 ) => {
      return orvalInstance<void>(
      {url: `/admin/avatars/${avatarId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 아바타 조회
 */
export const getAvatarControllerGetAvatar = (
    avatarId: string,
 ) => {
      return orvalInstance<AvatarAdminDto>(
      {url: `/admin/avatars/${avatarId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 아바타 수정
 */
export const updateAvatarControllerUpdateAvatar = (
    avatarId: string,
    updateAvatarAdminDto: UpdateAvatarAdminDto,
 ) => {
      return orvalInstance<AvatarAdminDto>(
      {url: `/admin/avatars/${avatarId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateAvatarAdminDto
    },
      );
    }
  
/**
 * @summary 닉네임 소스 생성
 */
export const createNicknameSourceControllerCreateNicknameSourceAdmin = (
    createNicknameSourceAdminDto: CreateNicknameSourceAdminDto,
 ) => {
      return orvalInstance<NicknameSourceAdminDto>(
      {url: `/admin/nickname-sources`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNicknameSourceAdminDto
    },
      );
    }
  
/**
 * @summary 닉네임 소스 리스트 조회
 */
export const listNicknameSourcesControllerListNicknameSources = (
    params?: ListNicknameSourcesControllerListNicknameSourcesParams,
 ) => {
      return orvalInstance<NicknameSourceCollectionAdminDto>(
      {url: `/admin/nickname-sources`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 닉네임 소스 삭제
 */
export const deleteNicknameSourceControllerDeleteNicknameSource = (
    nicknameSourceId: string,
 ) => {
      return orvalInstance<void>(
      {url: `/admin/nickname-sources/${nicknameSourceId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 닉네임 소스 조회
 */
export const getNicknameSourceControllerGetNicknameSourceAdmin = (
    nicknameSourceId: string,
 ) => {
      return orvalInstance<NicknameSourceAdminDto>(
      {url: `/admin/nickname-sources/${nicknameSourceId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 닉네임 소스 수정
 */
export const updateNicknameSourceControllerUpdateNicknameSource = (
    nicknameSourceId: string,
    updateNicknameSourceAdminDto: UpdateNicknameSourceAdminDto,
 ) => {
      return orvalInstance<NicknameSourceAdminDto>(
      {url: `/admin/nickname-sources/${nicknameSourceId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateNicknameSourceAdminDto
    },
      );
    }
  
/**
 * @summary 퀴즈 대량 생성
 */
export const createQuizzesControllerCreateQuizzesAdmin = (
    createQuizzesAdminDto: CreateQuizzesAdminDto[],
 ) => {
      return orvalInstance<QuizAdminDto[]>(
      {url: `/admin/quizzes`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createQuizzesAdminDto
    },
      );
    }
  
/**
 * @summary 퀴즈 목록 조회
 */
export const listQuizzesControllerListQuizzes = (
    params?: ListQuizzesControllerListQuizzesParams,
 ) => {
      return orvalInstance<QuizCollectionAdminDto>(
      {url: `/admin/quizzes`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 퀴즈 삭제
 */
export const deleteQuizControllerDeleteQuizAdmin = (
    quizId: string,
 ) => {
      return orvalInstance<void>(
      {url: `/admin/quizzes/${quizId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 퀴즈 단일 조회
 */
export const getQuizControllerGetQuizzesAdmin = (
    quizId: string,
 ) => {
      return orvalInstance<QuizAdminDto>(
      {url: `/admin/quizzes/${quizId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 퀴즈 수정
 */
export const updateQuizControllerUpdateQuizAdmin = (
    quizId: string,
    updateQuizAdminDto: UpdateQuizAdminDto,
 ) => {
      return orvalInstance<QuizAdminDto>(
      {url: `/admin/quizzes/${quizId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateQuizAdminDto
    },
      );
    }
  
/**
 * @summary 퀴즈 이미지 업로드
 */
export const createQuizImageControllerCreateQuizImageAdmin = (
    createQuizImageAdminDto: CreateQuizImageAdminDto,
 ) => {const formData = new FormData();
formData.append(`file`, createQuizImageAdminDto.file)
formData.append(`category`, createQuizImageAdminDto.category)
if(createQuizImageAdminDto.name !== undefined) {
 formData.append(`name`, createQuizImageAdminDto.name)
 }

      return orvalInstance<QuizImageAdminDto>(
      {url: `/admin/quiz-images`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * @summary 퀴즈 이미지 리스트 조회
 */
export const listQuizImagesControllerListQuizImagesAdmin = (
    params?: ListQuizImagesControllerListQuizImagesAdminParams,
 ) => {
      return orvalInstance<QuizImageCollectionAdminDto>(
      {url: `/admin/quiz-images`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 퀴즈 이미지 제거
 */
export const deleteQuizImageControllerDeleteQuizImage = (
    quizImageId: string,
 ) => {
      return orvalInstance<void>(
      {url: `/admin/quiz-images/${quizImageId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 퀴즈 이미지 단건 조회
 */
export const getQuizImageControllerGetQuizImage = (
    quizImageId: string,
 ) => {
      return orvalInstance<QuizImageAdminDto>(
      {url: `/admin/quiz-images/${quizImageId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 퀴즈 이미지 수정
 */
export const updateQuizImageControllerUpdateQuizImageAdmin = (
    quizImageId: string,
    updateQuizImageAdminDto: UpdateQuizImageAdminDto,
 ) => {
      return orvalInstance<QuizImageAdminDto>(
      {url: `/admin/quiz-images/${quizImageId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateQuizImageAdminDto
    },
      );
    }
  
/**
 * @summary 효과음 생성
 */
export const createSoundEffectControllerCreateSoundEffectAdmin = (
    createSoundEffectDto: CreateSoundEffectDto,
 ) => {const formData = new FormData();
formData.append(`file`, createSoundEffectDto.file)
if(createSoundEffectDto.name !== undefined) {
 formData.append(`name`, createSoundEffectDto.name)
 }
if(createSoundEffectDto.description !== undefined) {
 formData.append(`description`, createSoundEffectDto.description)
 }

      return orvalInstance<SoundEffectAdminDto>(
      {url: `/admin/sound-effects`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * @summary 효과음 리스트 조회
 */
export const listSoundEffectsControllerListSoundEffectsAdmin = (
    params?: ListSoundEffectsControllerListSoundEffectsAdminParams,
 ) => {
      return orvalInstance<SoundEffectCollectionAdminDto>(
      {url: `/admin/sound-effects`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 효과음 삭제
 */
export const deleteSoundEffectControllerDeleteSoundEffectAdmin = (
    soundEffectId: string,
 ) => {
      return orvalInstance<void>(
      {url: `/admin/sound-effects/${soundEffectId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 효과음 단일 조회
 */
export const getSoundEffectControllerGetSoundEffect = (
    soundEffectId: string,
 ) => {
      return orvalInstance<SoundEffectAdminDto>(
      {url: `/admin/sound-effects/${soundEffectId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 효과음 수정
 */
export const updateSoundEffectControllerUpdateSoundEffectAdmin = (
    soundEffectId: string,
    updateSoundEffectAdminDto: UpdateSoundEffectAdminDto,
 ) => {
      return orvalInstance<SoundEffectAdminDto>(
      {url: `/admin/sound-effects/${soundEffectId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSoundEffectAdminDto
    },
      );
    }
  
export type ListAccountsControllerListAccountsAdminResult = NonNullable<Awaited<ReturnType<typeof listAccountsControllerListAccountsAdmin>>>
export type CreateAvatarControllerCreateAvatarAdminResult = NonNullable<Awaited<ReturnType<typeof createAvatarControllerCreateAvatarAdmin>>>
export type ListAvatarsControllerListAvatarsResult = NonNullable<Awaited<ReturnType<typeof listAvatarsControllerListAvatars>>>
export type DeleteAvatarControllerDeleteAvatarAdminResult = NonNullable<Awaited<ReturnType<typeof deleteAvatarControllerDeleteAvatarAdmin>>>
export type GetAvatarControllerGetAvatarResult = NonNullable<Awaited<ReturnType<typeof getAvatarControllerGetAvatar>>>
export type UpdateAvatarControllerUpdateAvatarResult = NonNullable<Awaited<ReturnType<typeof updateAvatarControllerUpdateAvatar>>>
export type CreateNicknameSourceControllerCreateNicknameSourceAdminResult = NonNullable<Awaited<ReturnType<typeof createNicknameSourceControllerCreateNicknameSourceAdmin>>>
export type ListNicknameSourcesControllerListNicknameSourcesResult = NonNullable<Awaited<ReturnType<typeof listNicknameSourcesControllerListNicknameSources>>>
export type DeleteNicknameSourceControllerDeleteNicknameSourceResult = NonNullable<Awaited<ReturnType<typeof deleteNicknameSourceControllerDeleteNicknameSource>>>
export type GetNicknameSourceControllerGetNicknameSourceAdminResult = NonNullable<Awaited<ReturnType<typeof getNicknameSourceControllerGetNicknameSourceAdmin>>>
export type UpdateNicknameSourceControllerUpdateNicknameSourceResult = NonNullable<Awaited<ReturnType<typeof updateNicknameSourceControllerUpdateNicknameSource>>>
export type CreateQuizzesControllerCreateQuizzesAdminResult = NonNullable<Awaited<ReturnType<typeof createQuizzesControllerCreateQuizzesAdmin>>>
export type ListQuizzesControllerListQuizzesResult = NonNullable<Awaited<ReturnType<typeof listQuizzesControllerListQuizzes>>>
export type DeleteQuizControllerDeleteQuizAdminResult = NonNullable<Awaited<ReturnType<typeof deleteQuizControllerDeleteQuizAdmin>>>
export type GetQuizControllerGetQuizzesAdminResult = NonNullable<Awaited<ReturnType<typeof getQuizControllerGetQuizzesAdmin>>>
export type UpdateQuizControllerUpdateQuizAdminResult = NonNullable<Awaited<ReturnType<typeof updateQuizControllerUpdateQuizAdmin>>>
export type CreateQuizImageControllerCreateQuizImageAdminResult = NonNullable<Awaited<ReturnType<typeof createQuizImageControllerCreateQuizImageAdmin>>>
export type ListQuizImagesControllerListQuizImagesAdminResult = NonNullable<Awaited<ReturnType<typeof listQuizImagesControllerListQuizImagesAdmin>>>
export type DeleteQuizImageControllerDeleteQuizImageResult = NonNullable<Awaited<ReturnType<typeof deleteQuizImageControllerDeleteQuizImage>>>
export type GetQuizImageControllerGetQuizImageResult = NonNullable<Awaited<ReturnType<typeof getQuizImageControllerGetQuizImage>>>
export type UpdateQuizImageControllerUpdateQuizImageAdminResult = NonNullable<Awaited<ReturnType<typeof updateQuizImageControllerUpdateQuizImageAdmin>>>
export type CreateSoundEffectControllerCreateSoundEffectAdminResult = NonNullable<Awaited<ReturnType<typeof createSoundEffectControllerCreateSoundEffectAdmin>>>
export type ListSoundEffectsControllerListSoundEffectsAdminResult = NonNullable<Awaited<ReturnType<typeof listSoundEffectsControllerListSoundEffectsAdmin>>>
export type DeleteSoundEffectControllerDeleteSoundEffectAdminResult = NonNullable<Awaited<ReturnType<typeof deleteSoundEffectControllerDeleteSoundEffectAdmin>>>
export type GetSoundEffectControllerGetSoundEffectResult = NonNullable<Awaited<ReturnType<typeof getSoundEffectControllerGetSoundEffect>>>
export type UpdateSoundEffectControllerUpdateSoundEffectAdminResult = NonNullable<Awaited<ReturnType<typeof updateSoundEffectControllerUpdateSoundEffectAdmin>>>
